server.port=8085
spring.datasource.url: jdbc:mysql://localhost:3306/proxi-immo?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username: root
spring.datasource.password= Z8d=jJZ_
#spring.datasource.username: admin
#spring.datasource.password: 123Admin!
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-dir: ./uploads
# App Properties
bezkoder.app.jwtSecret= bezKoderSecretKey
bezkoder.app.jwtExpirationMs= 86400000
server.servlet.context-path=/proxi-immo-backend

